stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

test:
  stage: test
  image: node:14
  script:
    - npm install
    - npm test
  only:
    - master

deploy:
  stage: deploy
  image: alpine/helm:3.2.4
  script:
    - helm upgrade --install my-app-release my-chart/ --set image.tag=$IMAGE_TAG
  only:
    - master
  environment:
    name: production
